# Generated by Django 5.2.12 on 2026-04-02 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_rename_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
